version: '3.8'

services:
  news-aggregator:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
    restart: unless-stopped
    command: python main.py web

  # Scheduler service removed - using GitHub Actions for automation
  # See .github/workflows/ml-pipeline.yml for automated scheduling

volumes:
  data:
  models:
  logs: