name: news
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.*
  - pandas=1.5.*
  - scikit-learn=1.3.*
  - matplotlib=3.7.*
  - seaborn=0.12.*
  - requests=2.31.*
  - beautifulsoup4=4.12.*
  - lxml=4.9.*
  - nltk=3.8.*
  - flask=2.3.*
  - pyyaml=6.0.*
  - tqdm=4.65.*
  - joblib=1.3.*
  - pip:
    - torch>=2.0.0
    - feedparser>=6.0.0
    - newspaper3k>=0.2.8
    - transformers>=4.30.0
    - sentence-transformers>=2.2.0
    - flask-cors>=4.0.0
    - sqlalchemy>=2.0.0
    - python-dotenv>=1.0.0
    - schedule>=1.2.0
    - vaderSentiment>=3.3.2
    - textblob>=0.17.0
    - dvc>=3.0.0
    - gunicorn>=21.0.0