# Fly.io Deployment Configuration
app = "news-aggregator-YOUR_USERNAME"  # Change YOUR_USERNAME
primary_region = "ord"  # Chicago - change if needed

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  FLASK_ENV = "production"
  WEB_APP_HOST = "0.0.0.0"
  WEB_APP_PORT = "8080"
  DATABASE_URL = "sqlite:///data/news_database.db"
  HF_HUB_DISABLE_SYMLINKS_WARNING = "1"
  TOKENIZERS_PARALLELISM = "false"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = "news_data"
  destination = "/app/data"

[processes]
  app = "python main.py web"